{{ if .Values.tangodb.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: tangodb-{{ template "tango-example.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tangodb-{{ template "tango-example.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ template "tango-example.chart" . }}"
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
  clusterIP: None
  selector:
    app.kubernetes.io/name: tangodb-{{ template "tango-example.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tangodb-{{ template "tango-example.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tangodb-{{ template "tango-example.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ template "tango-example.chart" . }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tangodb-{{ template "tango-example.name" . }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  serviceName: tangodb-{{ template "tango-example.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tangodb-{{ template "tango-example.name" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        helm.sh/chart: "{{ template "tango-example.chart" . }}"
    spec:
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: tangodb
        image: "{{ .Values.tangodb.image.registry }}/{{ .Values.tangodb.image.image }}:{{ .Values.tangodb.image.tag }}"
        imagePullPolicy: {{ .Values.tangodb.image.pullPolicy }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ .Values.tangodb.db.rootpw }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.tangodb.db.db }}"
          - name: MYSQL_USER
            value: "{{ .Values.tangodb.db.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.tangodb.db.password }}"
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
{{ toYaml .Values.tangodb.resources | indent 10 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tangodb-{{ template "tango-example.name" . }}-{{ .Release.Name }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}
